# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesApp
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database’
pod 'Firebase/Core'


  target 'MoviesAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesAppUITests' do
    # Pods for testing
  end

end
