# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GradeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GradeApp
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
pod 'Firebase/Core'
pod 'Firebase/Storage'

  target 'GradeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GradeAppUITests' do
    # Pods for testing
  end

end
